# -*- coding: utf-8 -*-
"""Pricing Modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ti2hhYNh8htzGqmourTIUk2_xXBi-bsc

## **Import das Bibliotecas**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

from google.colab import files
uploaded = files.upload()

base = pd.read_excel("insurance_claims_ptBR (1) (1).xltx")

base

base.info()

base.isnull().sum()

"""# **Análise Exploratória de Dados**"""

# Concentração de idade dos segurados com curva de densidade
sns.histplot(base["idade"], kde=True)

base["idade"].describe()

# Anos como segurado
sns.histplot(base["anos_como_cliente"], kde=True)

base["anos_como_cliente"].describe()

sns.boxplot(y=base["anos_como_cliente"], color="skyblue")
plt.ylabel("Anos")
plt.show()
# Concentração de massa segurada entre 10 a 25 anos de companhia

sns.histplot(base["gravidade_incidente"], kde = True)

base["sexo_segurado"].hist()
# 56% da base de seguidores são do sexo feminino

base["sexo_segurado"].describe()

sns.histplot(base["valor_total_sinistro"], kde=True)

sns.boxplot(y=base["valor_total_sinistro"], color="skyblue")
plt.ylabel("Valor")
plt.show()
# USD 60.000 como valor médio de sinistro com uma variancia entre 40 a 80

base["valor_total_sinistro"].describe()

# HEATMAP de Correlação
colunas = [
     "valor_total_sinistro", "sexo_segurado", "anos_como_cliente", "local_incidente"
]

# Load original data again for correlation calculation to ensure original columns are present
base_for_corr = pd.read_excel("insurance_claims_ptBR (1) (1).xltx")
# Calculate 'anos_como_cliente' for base_for_corr, assuming it's derived from 'meses_como_cliente'
base_for_corr['anos_como_cliente'] = base_for_corr['meses_como_cliente'] / 12
df_corr = base_for_corr[colunas].copy()

le = LabelEncoder()
for col in df_corr.select_dtypes(include=['object']).columns:
    df_corr[col] = le.fit_transform(df_corr[col])

matriz_correlacao = df_corr.corr()

sns.heatmap(matriz_correlacao, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)

"""# **Entendimento de Padrões**"""

base["fraude_reportada"].value_counts()

base['fraude_reportada'].value_counts(normalize=True)

base['fraude_reportada'] = base['fraude_reportada'].map({'Y':1, 'N':0})

# Dumificação
base = pd.get_dummies(base, drop_first=True)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Separação de Treino e teste
X = base.drop(['fraude_reportada', 'data_emissao_apolice', 'data_incidente'], axis=1)
y = base['fraude_reportada']

le = LabelEncoder()
for column in X.select_dtypes(include=['object']).columns:
    X[column] = le.fit_transform(X[column])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""# **Processo de Modelagem**

1° Modelo Regressão Linear
"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# Aplicando balanceamento de classes
model = LogisticRegression(max_iter=5000, class_weight="balanced")
model.fit(X_train, y_train)

prob_fraude = model.predict_proba(X_test)[:,1]

from sklearn.metrics import classification_report

pred = model.predict(X_test)

print(classification_report(y_test, pred))

# Curva ROC
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, prob_fraude)

"""2° Modelo Random Forest"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

print(classification_report(y_test, rf.predict(X_test)) )

# Balanceament de classes
rf = RandomForestClassifier(class_weight="balanced", random_state=42)
rf = RandomForestClassifier(
    n_estimators=500,
    class_weight="balanced",
    random_state=42
)
rf.fit(X_train, y_train)

"""3° Modelo XGboost"""

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

xgb.fit(X_train, y_train)

pred_xgb = xgb.predict(X_test)
prob_xgb = xgb.predict_proba(X_test)[:,1]

from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, prob_xgb)